// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var LottieAnimatedExample = require("./LottieAnimatedExample.js");

function app() {
  return ReasonReact.element(/* None */0, /* None */0, LottieAnimatedExample.make(/* array */[]));
}

exports.app = app;
/* ReasonReact Not a pure module */
