// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var Picker$BsReactNative = require("bs-react-native/lib/js/src/components/picker.js");
var Platform$BsReactNative = require("bs-react-native/lib/js/src/platform.js");

var component = ReasonReact.statelessComponent("ExamplePicker");

function make(example, onChange, examples, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var match = Platform$BsReactNative.equals(/* IOS */[/* Phone */0]);
      return ReasonReact.element(/* None */0, /* None */0, Picker$BsReactNative.make(/* Some */[onChange], /* Some */[example[/* name */0]], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$BsReactNative.style(/* :: */[
                              match !== 0 ? Style$BsReactNative.marginBottom(/* Pt */Block.__(0, [-30.0])) : Style$BsReactNative.marginBottom(/* Pt */Block.__(0, [0.0])),
                              /* [] */0
                            ])], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[$$Array.map((function (example) {
                              return ReasonReact.element(/* Some */[example[/* name */0]], /* None */0, Picker$BsReactNative.Item[/* make */0](/* None */0, /* Some */[example[/* name */0]], /* Some */[example[/* name */0]], /* None */0)(/* array */[]));
                            }), examples)]));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
