// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Animated$BsReactNative = require("bs-react-native/lib/js/src/animated.js");
var LottieView$BsLottieReactNative = require("bs-lottie-react-native/lib/js/src/LottieView.js");

var component = ReasonReact.reducerComponent("LottieAnimatedExample");

var animations = {
  lottie1: ( require('./animations/LottieLogo1.json'))
};

function make() {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function (self) {
      Curry._3(Animated$BsReactNative.CompositeAnimation[/* start */1], Curry.app(Animated$BsReactNative.Value[/* Timing */19][/* animate */0], [
                self[/* state */2][/* progress */0],
                /* `raw */[
                  5690856,
                  1.0
                ],
                /* Some */[Animated$BsReactNative.Easing[/* linear */5]],
                /* Some */[10000.0],
                /* None */0,
                /* None */0,
                /* None */0,
                /* None */0,
                /* None */0,
                /* () */0
              ]), /* None */0, /* () */0);
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function (self) {
      return ReasonReact.element(/* None */0, /* None */0, LottieView$BsLottieReactNative.make(/* Local */Block.__(0, [animations.lottie1]), /* Some */[/* Animated */Block.__(0, [self[/* state */2][/* progress */0]])], /* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* array */[]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* progress */Curry._1(Animated$BsReactNative.Value[/* create */0], 0.0)];
    });
  newrecord[/* reducer */12] = (function (_, _$1) {
      return /* NoUpdate */0;
    });
  return newrecord;
}

exports.component = component;
exports.animations = animations;
exports.make = make;
/* component Not a pure module */
