// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Js_option = require("bs-platform/lib/js/js_option.js");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var LottieReactNative = require("lottie-react-native");

function sourceToJs(source) {
  switch (source.tag | 0) {
    case 0 : 
    case 1 : 
        return source[0];
    case 2 : 
        return {
                uri: source[0]
              };
    
  }
}

function progressToJs(progress) {
  return progress[0];
}

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -899416265,
    "cover"
  ],
  /* tuple */[
    98248149,
    "center"
  ],
  /* tuple */[
    427065300,
    "contain"
  ]
];

function resizeModeToJs(param) {
  return Js_mapperRt.binarySearch(3, param, jsMapperConstantArray);
}

function resizeModeFromJs(param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray, param);
}

function make(source, progress, speed, autoPlay, loop, resizeMode, children) {
  var tmp = {
    source: sourceToJs(source)
  };
  var tmp$1 = Js_option.map((function (progress) {
          return progress[0];
        }), progress);
  if (tmp$1) {
    tmp.progress = tmp$1[0];
  }
  if (speed) {
    tmp.speed = speed[0];
  }
  var tmp$2 = Js_option.map(Js_boolean.to_js_boolean, autoPlay);
  if (tmp$2) {
    tmp.autoPlay = tmp$2[0];
  }
  var tmp$3 = Js_option.map(Js_boolean.to_js_boolean, loop);
  if (tmp$3) {
    tmp.loop = tmp$3[0];
  }
  var tmp$4 = Js_option.map(resizeModeToJs, resizeMode);
  if (tmp$4) {
    tmp.resizeMode = tmp$4[0];
  }
  return ReasonReact.wrapJsForReason(LottieReactNative, tmp, children);
}

exports.sourceToJs = sourceToJs;
exports.progressToJs = progressToJs;
exports.resizeModeToJs = resizeModeToJs;
exports.resizeModeFromJs = resizeModeFromJs;
exports.make = make;
/* ReasonReact Not a pure module */
