// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Js_option = require("bs-platform/lib/js/js_option.js");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var LottieReactNative = require("lottie-react-native");

function optBoolToOptJsBoolean(optValue) {
  return Js_option.map(Js_boolean.to_js_boolean, optValue);
}

function sourceToJs(source) {
  if (source.tag === 3) {
    return {
            uri: source[0]
          };
  } else {
    return source[0];
  }
}

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -899416265,
    "cover"
  ],
  /* tuple */[
    98248149,
    "center"
  ],
  /* tuple */[
    427065300,
    "contain"
  ]
];

function make(source, progress, speed, autoPlay, loop, style, resizeMode, imageAssetsFolder, hardwareAccelerationAndroid, enableMergePathsAndroidForKitKatAndAbove, children) {
  var tmp = {
    source: sourceToJs(source)
  };
  var tmp$1 = Js_option.map((function (progress) {
          return progress[0];
        }), progress);
  if (tmp$1) {
    tmp.progress = tmp$1[0];
  }
  if (speed) {
    tmp.speed = speed[0];
  }
  var tmp$2 = optBoolToOptJsBoolean(autoPlay);
  if (tmp$2) {
    tmp.autoPlay = tmp$2[0];
  }
  var tmp$3 = optBoolToOptJsBoolean(loop);
  if (tmp$3) {
    tmp.loop = tmp$3[0];
  }
  if (style) {
    tmp.style = style[0];
  }
  var tmp$4 = Js_option.map((function (mode) {
          return Js_mapperRt.binarySearch(3, mode, jsMapperConstantArray);
        }), resizeMode);
  if (tmp$4) {
    tmp.resizeMode = tmp$4[0];
  }
  if (imageAssetsFolder) {
    tmp.imageAssetsFolder = imageAssetsFolder[0];
  }
  var tmp$5 = optBoolToOptJsBoolean(hardwareAccelerationAndroid);
  if (tmp$5) {
    tmp.hardwareAccelerationAndroid = tmp$5[0];
  }
  var tmp$6 = optBoolToOptJsBoolean(enableMergePathsAndroidForKitKatAndAbove);
  if (tmp$6) {
    tmp.enableMergePathsAndroidForKitKatAndAbove = tmp$6[0];
  }
  return ReasonReact.wrapJsForReason(LottieReactNative, tmp, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
