// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Js_option = require("bs-platform/lib/js/js_option.js");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");

function optBoolToOptJsBoolean(optValue) {
  return Js_option.map(Js_boolean.to_js_boolean, optValue);
}

exports.optBoolToOptJsBoolean = optBoolToOptJsBoolean;
/* No side effect */
