// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");

function makeExample(width, name, getJson) {
  return /* record */[
          /* name */name,
          /* getJson */getJson,
          /* width */width
        ];
}

var examples = /* array */[
  /* record */[
    /* name */"Hamburger Arrow",
    /* getJson */(function () {
        return /* Required */Block.__(2, [require("./animations/HamburgerArrow.json")]);
      }),
    /* width : None */0
  ],
  /* record */[
    /* name */"Hamburger Arrow (200 px)",
    /* getJson */(function () {
        return /* Required */Block.__(2, [require("./animations/HamburgerArrow.json")]);
      }),
    /* width : Some */[200]
  ],
  /* record */[
    /* name */"Line Animation",
    /* getJson */(function () {
        return /* Required */Block.__(2, [require("./animations/LineAnimation.json")]);
      }),
    /* width : None */0
  ],
  /* record */[
    /* name */"Lottie Logo 1",
    /* getJson */(function () {
        return /* Required */Block.__(2, [require("./animations/LottieLogo1.json")]);
      }),
    /* width : None */0
  ],
  /* record */[
    /* name */"Lottie Logo 2",
    /* getJson */(function () {
        return /* Required */Block.__(2, [require("./animations/LottieLogo2.json")]);
      }),
    /* width : None */0
  ],
  /* record */[
    /* name */"Lottie Walkthrough",
    /* getJson */(function () {
        return /* Required */Block.__(2, [require("./animations/LottieWalkthrough.json")]);
      }),
    /* width : None */0
  ],
  /* record */[
    /* name */"Pin Jump",
    /* getJson */(function () {
        return /* Required */Block.__(2, [require("./animations/PinJump.json")]);
      }),
    /* width : None */0
  ],
  /* record */[
    /* name */"Twitter Heart",
    /* getJson */(function () {
        return /* Required */Block.__(2, [require("./animations/TwitterHeart.json")]);
      }),
    /* width : None */0
  ],
  /* record */[
    /* name */"Watermelon",
    /* getJson */(function () {
        return /* Required */Block.__(2, [require("./animations/Watermelon.json")]);
      }),
    /* width : None */0
  ],
  /* record */[
    /* name */"Motion Corpse",
    /* getJson */(function () {
        return /* Required */Block.__(2, [require("./animations/MotionCorpse-Jrcanest.json")]);
      }),
    /* width : None */0
  ]
];

function findByName(name) {
  return List.find((function (example) {
                return +(example[/* name */0] === name);
              }), $$Array.to_list(examples));
}

exports.makeExample = makeExample;
exports.examples = examples;
exports.findByName = findByName;
/* No side effect */
